### ISSUE TITLE
Duplicar informe

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#1]
Aprovecho un correo de uno de nuestros colaboradores para estrenar este foro. M.A.  Dice:

> Nos ha preguntado un usuario por la posibilidad de duplicar un informe dentro de un mismo archivo. ¿No existe esa posibilidad en Crono Analysis 19.45.3?

![image](https://user-images.githubusercontent.com/4572969/78782514-73a3d100-79a2-11ea-9c1c-bdc20d43b3ad.png)

> En la versión antigua si que estaba disponible esa opción :

![image](https://user-images.githubusercontent.com/4572969/78782569-83bbb080-79a2-11ea-8e75-26f6c5f14ce3.png)

**Comment by bifacil** [comment]
Actualmente esta funcionalidad no está disponible. Tomamos nota e incorporaremos esta funcionalidad pronto.

De momento, existe la funcionalidad de “Importar” y os puede servir de “workaround”:

![image](https://user-images.githubusercontent.com/4572969/78782830-e7de7480-79a2-11ea-859b-5052eff992aa.png)

Los pasos a seguir son:

-	Hacer una copia del documento .rep original
-	Abrir el informe original y hacer clic en “Importar” del menú contextual
-	Selecciona el documnento .rep copiado en el paso 1
-	Os aparecerá una ventana y tendréis que seleccionar el informe que queréis importar/duplicar.

De este modo, el informe quedará duplicado en el documento inicial…

**Comment by sergiodebst** [comment]
Esta funcionalidad estára disponible en la siguiente versión de Crono Analysis:
![imagen](https://user-images.githubusercontent.com/5172886/80075623-467f2300-854b-11ea-8b95-caaf1db9c04a.png)

**Comment by bifacil** [comment]
La versión 20.18 incorpora esta nueva funcionalidad. Ya está publicada.

Cerramos el caso.
