### ISSUE TITLE
Nuevas funcionalidades Crono Web

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#10]
J. nos sugiere tres nuevas funcionalidades en Crono Web:

1. Formatos condicionales
2. Selección obligatoria (impide que se ejecuten paneles dependientes a menos que haya una selección) (esta funcionalidad está en **Crono Analysis**)
3. Formato URL (como en **Crono Analysis**)

**Comment by bifacil** [comment]
El tema de la selección obligatoria ya está disponible a partir de la versión 20.47. También hemos añadido otras de las configuraciones disponibles en Crono Analysis:

![image](https://user-images.githubusercontent.com/4572969/99583518-e3bc1000-29e3-11eb-93b3-a9d270a0c040.png)

**Comment by trebsoj** [comment]
He abierto un issue, para el punto 1 y 3 así queda un poco más separado y es más fácil de buscar ;)

**Comment by bifacil** [comment]
> He abierto un issue, para el punto 1 y 3 así queda un poco más separado y es más fácil de buscar ;)

OK. Mejor así.

Cierro esta incidencia.
