### ISSUE TITLE
Algunos literales incorrectamente traducidos al catalán ("Guardar como")

### ISSUE THREAD

**Issue by jordimontanes** [bifacil/CronoSupport#111]
Els actuals literals que es mostren, en la versió en català de Crono Analysis, generen confusió:
![image](https://github.com/crono-bi/CronoSupport/assets/122264577/7105f84d-61b1-4adb-8d5d-cedca1f8d2a8)

En altres aplicacions els literals que apareixen són els següents:
![image](https://github.com/crono-bi/CronoSupport/assets/122264577/1acd399e-3463-4721-8f88-80a3d12bee72)

Caldria modificar els literals per tal que l'usuari no tingui dubtes.

**Comment by bifacil** [comment]
En la próxima actualización ya aparecerá correctamente:

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/c06a8ad2-fcc4-4165-8cad-58c1a866c16a)

Al final hemos preferido la palabra "Guardar" en lugar de "Desar", pues es igualmente correcto según DIEC, y su uso está más extendido.

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/aae04a1e-2c74-4efd-a9f7-e28ce09d847f)


![image](https://github.com/crono-bi/CronoSupport/assets/4572969/1cbe4751-6902-46cf-aba8-2a93135844da)
