### ISSUE TITLE
Crono Analysis 20.48 - Seleccionar catálogo en vista árbol

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#12]
Crono Analysis 20.48

No se muestra en forma de arbol, se muestra todo como si fuera un lista.

![Screenshot_1](https://user-images.githubusercontent.com/75248426/100598132-9bafbe00-32fe-11eb-8a27-ee4b42288d44.png)

**Comment by bifacil** [comment]
Era un problema del servidor. Está solucionado en la versión 20,48 (del servidor).

Si aún aparece mal, haz clic en "Actualizar lista".

![image](https://user-images.githubusercontent.com/4572969/100605999-0fef5f00-3309-11eb-9587-e7a4f909f783.png)

Cierro.
