### ISSUE TITLE
Crono Web - Formato Hipervínculo

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#13]
No existe este formato en Crono Web, en Crono Analysis sí existe.

Crono Web:
![Screenshot_1](https://user-images.githubusercontent.com/75248426/100599104-e41bab80-32ff-11eb-99e1-669db648a064.png)

Crono Analysis
![Screenshot_2](https://user-images.githubusercontent.com/75248426/100599130-eaaa2300-32ff-11eb-9ba3-041258e1cef9.png)

**Comment by bifacil** [comment]
Ok. Lo haremos en breve.

Se aprovechará la misma lógica y ocnfiguración que se usa en Crono analysis:

![image](https://user-images.githubusercontent.com/4572969/100773220-dd289200-3400-11eb-86fa-915e869613a3.png)

**Comment by bifacil** [comment]
Hemos incoporado esta funcionalidad en la versión 20.49.6890:

![image](https://user-images.githubusercontent.com/4572969/101201196-a1433600-3667-11eb-9e88-a6a30dc1aac0.png)


También aparece como un formato adicional:

![image](https://user-images.githubusercontent.com/4572969/101201446-0d259e80-3668-11eb-99bf-55a50210ca27.png)
