### ISSUE TITLE
Crono Web - Sugerencia informes readonly (HideMenu)

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#14]
Aprovechando la potencia de abrir un informe de crono con un link creo que sería interesante, que se pudiera pasar por ejemplo una variable en la url estilo (?readonly=true) y que en el informe no se visualizara ni panel de la izquierda, ni el título, ni el botón de modificar informe.

Así los usuarios podrían abrir informes (vía aplicaciones externas) y solo verían el informe en sí, sin opciones ni nada ...

Junto imágenes para que se entienda mejor:

**Normal**
![Screenshot_1](https://user-images.githubusercontent.com/75248426/100600034-0c57da00-3301-11eb-9848-7c7d5e01e642.png)

**Con parametro ?readonly=true**
![Screenshot_2](https://user-images.githubusercontent.com/75248426/100600039-0eba3400-3301-11eb-9c1a-5ec236b36779.png)

**Comment by trebsoj** [comment]
Otra opción también podría ser, la de poder mandar 2 variables (por ejemplo), uno para poder esconder el menú de la izquierda y otra variable para indicar que ese informe no se debe abrir en modo diseño.

Quizás sería más fácil, ya que son acciones que ya se pueden hacer ahora.

La url podría ser de la siguiente forma:

xxx?menu=false&design_mode=false

**Comment by bifacil** [comment]
Añadiremos una marca de "Hide Menu" para ocultar el menú:

![image](https://user-images.githubusercontent.com/4572969/110139705-9c5f6100-7dd3-11eb-821c-29550f165425.png)


Esto lo implementaremos con un "qury string" en la url (`HideMenu`), pero debe quedar claro que es un tema estético, y que no tiene implicaciones de seguridad o privacidad. Si el usuario modifica la url podrá acceder al informe en modo normal... (con el menú)

**Comment by bifacil** [comment]
La versión 21.10 incorpora esta funcionalidad.

Añadiendo la marca `?hm` al final de la URL se abrte el informe sin los menús visibles. De este modo, se muestra el informe y se limitan las posibilidades de interacción del usuario (quedando un UI más sencillo, etc.).

![image](https://user-images.githubusercontent.com/4572969/110453593-96fd6180-80c6-11eb-97f8-7756623194d5.png)

Si confirmas que os funciona, cerramos @trebsoj

**Comment by bifacil** [comment]
Cierro
