### ISSUE TITLE
Crono Web - Formato condicional

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#15]
Sería interesante poder poner formatos condicionales en crono web, de la misma forma que en crono Analysis.

![Screenshot_1](https://user-images.githubusercontent.com/75248426/100600655-d9621600-3301-11eb-8ae2-af9cf1388c07.png)

**Comment by bifacil** [comment]
Vamos a incorporar esta funcionalidad. Al menos de entrada no será tan potente como Crono Analysis, pero cubrirá las funcionalidades más habituales.

Lo describo a continuación.


![image](https://user-images.githubusercontent.com/4572969/106823252-e6441280-6680-11eb-96d4-2545b428f9b9.png)

![image](https://user-images.githubusercontent.com/4572969/106823592-85690a00-6681-11eb-8ad9-402a9b0b9252.png)

![image](https://user-images.githubusercontent.com/4572969/106824081-57d09080-6682-11eb-9d6b-24322d46ac4c.png)



Será funcionalmente similar a esto:

![image](https://user-images.githubusercontent.com/4572969/106823390-2acfae00-6681-11eb-946d-66cf77e69b19.png)

![image](https://user-images.githubusercontent.com/4572969/106824507-43d95e80-6683-11eb-80f0-babe13d9fc38.png)

Comentamos

**Comment by bifacil** [comment]
En la próxima actualización ya se podrán definir formatos condicionales.

![image](https://user-images.githubusercontent.com/4572969/109299618-a9a9a800-7835-11eb-937d-4432db1d7335.png)

Son más sencillos que los de Crono Analysis, pero son flexibles y cubren las funcional más común.

![image](https://user-images.githubusercontent.com/4572969/109299664-baf2b480-7835-11eb-8c48-f2d6fd7d8135.png)


Los formatos condicionales se definen desde las propiedades de columna:

![image](https://user-images.githubusercontent.com/4572969/109299728-dc53a080-7835-11eb-8360-ef9689bd8124.png)

Cada regla consta de una expresión y un selector de 5 formatos disponibles predefinidos:

![image](https://user-images.githubusercontent.com/4572969/109299844-05743100-7836-11eb-95e8-f98491f29b3c.png)

**Comment by bifacil** [comment]
La versión 21.8 ya incorpora esta funcionalidad.

Cerramos.

**Comment by bifacil** [comment]
Lo hemos hecho pensando en futuras ampliaciones. En el futuro se podrían poner gradientes, emojis, etc..., completando la funcionalidad existente en Crono Analysis.

Lo priorizaremos según las demandas existentes...
