### ISSUE TITLE
Crono Web - Ordenación columnas

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#16]
En Analysis cuando creas un informe la ordenación de las columnas se guarda, en Web no.

**Comment by bifacil** [comment]
![image](https://user-images.githubusercontent.com/4572969/115916228-ce587f80-a474-11eb-84a6-261d8d99136f.png)

**Comment by bifacil** [comment]
Este es el modelo del componente tabla de vuetify...

![image](https://user-images.githubusercontent.com/4572969/115915292-6d7c7780-a473-11eb-9c1a-0e8481e3f854.png)

Aquí estará la opción para seleccionala ordenación múltiple:

![image](https://user-images.githubusercontent.com/4572969/115915540-bf250200-a473-11eb-9074-688978412e3d.png)

![image](https://user-images.githubusercontent.com/4572969/115916342-fb0c9700-a474-11eb-9e30-cb0bf4c2d965.png)

**Comment by bifacil** [comment]
Deberemos pensar también este caso. ¿Queremos poder ordenar los gráficos? Si se ordena la tabla y se cambia a formato gráfico, ¿Se debe respetar la ordenación? Parece evidente que sí...

![image](https://user-images.githubusercontent.com/4572969/115916671-63f40f00-a475-11eb-8141-5d3a94647919.png)


![image](https://user-images.githubusercontent.com/4572969/115916911-c1885b80-a475-11eb-8dba-e2960036a81c.png)

**Comment by bifacil** [comment]
Esto ya funciona:

![image](https://user-images.githubusercontent.com/4572969/190245110-a6723a0b-604d-495f-ab97-7ad0733fc63b.png)

![image](https://user-images.githubusercontent.com/4572969/190245236-7da51b00-b7d3-45ac-9b2e-2c87d17ae1d0.png)


Aunque está pendiente de publicación.

**Comment by bifacil** [comment]
Publicada versión 22.37
