### ISSUE TITLE
Web - Error filtro

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#17]
Tengo una subconsulta con un filtro y al modificar los valores que debe filtrar no actualiza la tabla.

![screen](https://user-images.githubusercontent.com/75248426/101167086-aa1d1300-3639-11eb-940c-b6de533b5ca8.gif)

**Comment by bifacil** [comment]
Es verdad. Este bug ya lo detectamos aquí: https://github.com/bifacil/CronoSupport/issues/9#issuecomment-720370644

**Comment by bifacil** [comment]
Solucionado en Crono Server 20.49.8000.
