### ISSUE TITLE
Ordenación descendente de las listas de valores

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#2]
Un cliente nos envía la siguiente sugerencia:

> Cuando sale una lista de valores, sobre todo en el caso de fechas o años, ¿no estaría bien que salieran en orden descendente? ... siempre tienes que ir a buscar los últimos de la lista, que son los años más nuevos.

![image](https://user-images.githubusercontent.com/4572969/79320308-eca6a980-7f09-11ea-9047-7077c02448d4.png)

**Comment by bifacil** [comment]
Actualmente esta funcionalidad no está disponible. Desde el catálogo se puede configurar el campo de ordenación, pero la ordenación siempre es ascendente:

![image](https://user-images.githubusercontent.com/4572969/79320732-8e2dfb00-7f0a-11ea-82c1-ed4bf30af173.png)

Asi se explica en el manual de Crono Metadata: https://github.com/bifacil/CronoSupport/wiki/Listas-de-valores

De todos modos, nos parece una buena sugerencia, y la añadiremos en futuras versiones:

![image](https://user-images.githubusercontent.com/4572969/79320938-dea55880-7f0a-11ea-9b52-b94150246f49.png)

De momento, el _workaround_ es preparar un campo en la base de datos con el orden invertido. Es decir, por ejemplo, numerar los meses de este modo: -1, -2, -3, ...

**Comment by sergiodebst** [comment]
Está funcionalidad estará disponible en la próxima actualización, y se podrá configurar desde propiedades de objeto en Crono Metadata:
![IMG-20200422-WA0015](https://user-images.githubusercontent.com/5172886/80074903-27cc5c80-854a-11ea-844e-3080807a71b2.jpg)

**Comment by bifacil** [comment]
La versión 20.18 incorpora esta nueva funcionalidad. Ya está publicada.

Cerramos el caso.
