### ISSUE TITLE
Exportación de datos

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#22]
Opción para exportar los datos de un panel/informe.

Tal como se puede hacer en Analysis.

**Comment by bifacil** [comment]
Efectivamente esta opción no existe aún. 

![image](https://user-images.githubusercontent.com/4572969/106168787-f9417900-618e-11eb-9ca5-96782bbef985.png)

**Comment by bifacil** [comment]
Ya existe la opción de "Exportar a Excel":

![image](https://user-images.githubusercontent.com/4572969/106871625-b6255f80-66d2-11eb-854b-95c0cf5c8cb7.png)

La opción de copiar como imagen la hemos descartado de momento. No es prioritario en este momento, ya que una vez en Excel se puede formatear y copiar como se desee...

**Comment by bifacil** [comment]
Pendiente: La opción de exportar debería estar visible tambien en modo visualización (solo lectura)

**Comment by bifacil** [comment]
Ahora es posible exportar datos en el modo visualización (incluso en los usuarios que no tienen permiso de edición)

![image](https://user-images.githubusercontent.com/4572969/108506446-144c6800-72b9-11eb-8a14-7d22819e8179.png)

**Comment by trebsoj** [comment]
No exporta el pie de tabla, los totales, recuento .....

Puedes volver a reabrir ?

**Comment by bifacil** [comment]
Ok. Reabrimos el issue.

De todos modos, no creo que lo mejoremos inmediatamente, ya que para añadir esta funcionalidad utilizamos la "community edition" de ShhetJS  https://docs.sheetjs.com/ que no soporta la personalización estética del Excel generaod.

Solicitamos un presupuesto de la versión "Pro" (que permite colorear las celdas...) y nos presentaron una oferta ridículamente elevada...

Estudiaremos alternativas....

**Comment by trebsoj** [comment]
Las columnas numéricas de crono se importan a excel como texto, ya que excel no te deja hacer operaciones sobre esos campos, ya que no los considera números.

**Comment by bifacil** [comment]
Este tema estará resuelto en la próxima versión. Ahora se exportaran los valores no formateados. De este modo se podrán sumar o aplicar otros tratamientos...

![image](https://user-images.githubusercontent.com/4572969/110526692-65ac8200-8116-11eb-945a-892157f29839.png)

**Comment by bifacil** [comment]
Está publicado. Cerramos.
