### ISSUE TITLE
Crono web - Función de agregación

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#23]
No funciona la función de agregación cuando el campo no es un indicador.

Por ejemplo tengo una columna con códigos y quiero que me ponga un agregador con el total de los códigos (contador),
lo configuro y nunca sale en el pie de la tabla.

Si tengo un campo numérico, pero que no está marcado como indicador en el catálogo, tampoco se pueden hacer sumatorios por ejemplo.

Adjunto imágenes.

![Screenshot_1](https://user-images.githubusercontent.com/75248426/106121423-da73c000-6157-11eb-8a20-cd0c2e4d053a.png)
![Screenshot_2](https://user-images.githubusercontent.com/75248426/106121428-dba4ed00-6157-11eb-931a-3004a7e70f9e.png)

**Comment by bifacil** [comment]
Esto está resuelto en la versión 21.5.4900:

![image](https://user-images.githubusercontent.com/4572969/106874086-757b1580-66d5-11eb-8a38-1cc92eb94113.png)

Cierro
