### ISSUE TITLE
Crono web - Modo oscuro no funciona

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#24]
He activado el modo oscuro en la configuración del servidor y no veo ningún cambio.

**Comment by bifacil** [comment]
Se ha de configurar desde "Propiedades de usuario":

![image](https://user-images.githubusercontent.com/4572969/106158914-88955f00-6184-11eb-8b95-8dbe9116579b.png)


La configuración de servidor es solo la configuración predeterminada para usuarios nuevos. Luego cada usuario tiene se configuración.

![image](https://user-images.githubusercontent.com/4572969/106159100-bd091b00-6184-11eb-9e43-a6333903786f.png)


Cierro
