### ISSUE TITLE
Crono web - Filtros avanzados

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#25]
Solo se pueden hacer filtros 'simples' de valores que contenga esa dimensión.

Estaría muy bien poder hacer filtros avanzados, como en analysis, para poder escribir directamente la condición del filtro, o hacer comparaciones entre campos del catálogo, ......

![Screenshot_1](https://user-images.githubusercontent.com/75248426/106152529-d35fa880-617d-11eb-8443-412bb5f32092.png)

**Comment by bifacil** [comment]
Efectivamente, esta opción aún no está disponible. La añadiremos próximamente aquí:

![image](https://user-images.githubusercontent.com/4572969/106162796-ca280900-6188-11eb-9278-37004515b36a.png)

El editor de fórmulas tendrá un aspecto similar al del editor de columna:

![image](https://user-images.githubusercontent.com/4572969/106162981-f6dc2080-6188-11eb-88d1-77aa043e0471.png)

![image](https://user-images.githubusercontent.com/4572969/106163297-4a4e6e80-6189-11eb-9245-6213fcf1a307.png)

![image](https://user-images.githubusercontent.com/4572969/106163589-a2857080-6189-11eb-9a86-aa4b1bf0c820.png)

**Comment by bifacil** [comment]
La versión Crono Web 21.5 ya contiene los filtros avanzados. El formulario se ha modificado y ahora se parece más al de Crono Analysis:

![image](https://user-images.githubusercontent.com/4572969/106600284-7b002080-655a-11eb-9375-3299c40e564c.png)

**Comment by bifacil** [comment]
Cierro.
