### ISSUE TITLE
Filtros predefinidos

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#26]
No funcionan los filtros predefinidos (que estan creados en el catalogo directamente)

**Comment by bifacil** [comment]
Efectivamente no funciona. Lo solucionaremos en breve:

![image](https://user-images.githubusercontent.com/4572969/106165276-399ef800-618b-11eb-8820-4baf7b1c2f98.png)

**Comment by bifacil** [comment]
Parece un problema del backend. 

![image](https://user-images.githubusercontent.com/4572969/106166576-9bac2d00-618c-11eb-8905-f2fc843a9d52.png)

**Comment by bifacil** [comment]
Ya funciona en la versión 21.4.5000

![image](https://user-images.githubusercontent.com/4572969/106175150-13328a00-6196-11eb-8d0b-1df2f5d95d1b.png)

Cierro

**Comment by bifacil** [comment]
Cierro
