### ISSUE TITLE
Bloquear actualizaciones automáticas

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#3]
El colaborador C.R. nos pide añadir la opción de bloquear las actualizaciones automáticas (también en Crono Metadata y Crono Administrador):

![image](https://user-images.githubusercontent.com/4572969/84163217-86ee1e00-aa71-11ea-9eb8-de7dcfe012d4.png)

**Comment by bifacil** [comment]
Las actualizaciones son automáticas porque asumimos que las versiones más recientes tienen más funcionalidades y resuelven problemas de las versiones antiguas. Antes de publicar ninguna versión se pasa un conjunto completo de pruebas para asegurar que no existe ninguna regresión.

También vigilamos mucho no introducir "breaking changes". Un catálogo guardado con una versión reciente de Crono Metadata debe funcionar con una versión más antigua de Crono Analysis. Cada producto sigue su propio ritmo de actualización y no hay necesidad de que las versiones sean idénticas.

En cualquier caso, **entendemos la necesidad, y valoraremos esta petición próximamente.**

**Comment by sergiodebst** [comment]
Se ha añadido la opción en "Opciones generales".
![imagen](https://user-images.githubusercontent.com/5172886/84658729-9dcfbd00-af16-11ea-9956-9289e3d53617.png)

**Comment by bifacil** [comment]
![image](https://user-images.githubusercontent.com/4572969/85993704-0464d880-b9f7-11ea-8bfb-b40932be5af1.png)

**Comment by bifacil** [comment]
Esto ya esta:

![image](https://user-images.githubusercontent.com/4572969/85993857-3ece7580-b9f7-11ea-81a8-99a858ffa845.png)

**Comment by bifacil** [comment]
Hola, 

En relación a este issue se han tomado dos acciones:

- Se ha creado el MSI de Crono Metadata y Crono Administrador. Se pueden descargar desde http://downloads.crono.net/
- Para la instalación normal (Standard Release o _Squirrel_), se ha añadido una marca para deshabilitar opcionalmente las actualizaciones automáticas.

![image](https://user-images.githubusercontent.com/4572969/86029850-000ae080-ba34-11ea-996b-f6c457c51c86.png)

**Comment by bifacil** [comment]
Cerramos el issue.
