### ISSUE TITLE
Crono web - Error width columnas

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#31]
En contenido de las columnas no se muestra bien cuando hay varias columnas y el contenido es un poco largo
![Screenshot_1](https://user-images.githubusercontent.com/75248426/109520921-0367d780-7aad-11eb-8771-1719af57f47b.png)

También pasa que si hay muchas columnas, no sale ningún scroll horizontal y se ven bastante mal

**Comment by bifacil** [comment]
Hemos podido reproducirlo:

![image](https://user-images.githubusercontent.com/4572969/110134077-4edff580-7dcd-11eb-9553-a5b263e489bc.png)


Hay varias soluciones posibles ante este problemas:


1.- Scroll horizontal (como sugieres)
2. Truncar el valor (mostrando el valor completo en un tooltip)
3. Ajustar el alto automáticamente, para que queda íntegro el texto que sea.
4. Establecer de algún modo el ancho de cada columna (ahora se calcula autom´çaticamente)

En Crono Analysis se aplica la solución [3], ajustando el alto:

![image](https://user-images.githubusercontent.com/4572969/110134729-02e18080-7dce-11eb-9ec6-13d78129f3a8.png)


![image](https://user-images.githubusercontent.com/4572969/110135991-73d56800-7dcf-11eb-8236-205d0379f8e2.png)


**ESTUDIAREMOS LAS ALTERNATIVAS ANTES DE DECIDIR**

**Comment by bifacil** [comment]
![image](https://user-images.githubusercontent.com/4572969/110353339-3d9a2180-8037-11eb-9aaa-f1d9b388d80a.png)

![image](https://user-images.githubusercontent.com/4572969/110353464-628e9480-8037-11eb-8078-875085a31e42.png)




Hemos probados las distintas altenativas y pensamis que la mejor es replicar la misma solución de Crono Analysis (saltos de línea automáticos...).

Estará disponible en la próxima actualización.

Así funcionará:

![image](https://user-images.githubusercontent.com/4572969/110374033-75fa2980-8050-11eb-8a39-67ccf9638b26.png)

**Comment by bifacil** [comment]
La versión 21.10 ya está publicada y corrige este comportamiento.

![image](https://user-images.githubusercontent.com/4572969/110453280-4ab22180-80c6-11eb-9d39-8d091ec6c432.png)


Si confirmas que os funciona, cerramos @trebsoj

**Comment by bifacil** [comment]
Cierro.
