### ISSUE TITLE
Limites en los graficos

### ISSUE THREAD

**Issue by carlosromeroreija** [bifacil/CronoSupport#33]
En la versión antigua de se podía jugar con parametros de las escalas de los graficos tales como los limites de las eliminar valores muy altos, bajos etc...   

Es posible establecer estas características en la nueva versión?

**Comment by bifacil** [comment]
Efectivamente, estas eran las opciones en Crono Classic:

![image](https://user-images.githubusercontent.com/4572969/110329218-99a37c80-801c-11eb-8b7e-ff360f168764.png)


![image](https://user-images.githubusercontent.com/4572969/110329383-cc4d7500-801c-11eb-9dae-f58bcda8074e.png)

Tomamos notas y lo mejoraremos ASAP.

**Comment by bifacil** [comment]
![image](https://user-images.githubusercontent.com/4572969/110838785-29f2f300-82a3-11eb-9539-53e8046283e9.png)

De hecho, pod´riamos ponerlo en "Propiedades panel":

![image](https://user-images.githubusercontent.com/4572969/110839125-8524e580-82a3-11eb-95f3-a2d60068aba6.png)

**Comment by bifacil** [comment]
En la última actualización, desde "Opciones gráfico" (en "Propiedades panel") se puede configurar el máximo y el mínimo del eje:

![image](https://user-images.githubusercontent.com/4572969/113675793-0497b000-96bc-11eb-9809-1ab46f1fda07.png)


![image](https://user-images.githubusercontent.com/4572969/113675944-2ee96d80-96bc-11eb-9abb-7ad2728485e4.png)

Cerramos.
