### ISSUE TITLE
Crono Analysis - No abre los informes des del explorador de archivos

### ISSUE THREAD

**Issue by trebsoj** [bifacil/CronoSupport#34]
Cuando un usuario hace doble click en un informe de crono, la aplicación no abre el informe, abre el crono pero en blanco.

**Comment by bifacil** [comment]
Hola, 

El problema ya está resuelto en la versión 21.38.2000

La incidencia solo se producía cuando se intentaba abrir un informe **desde el explorador de archivos** y cuando ya existía otro informe abierto (el primero se abría correctamente).

Aprovecho para recordar que el setup no asocia la extensión `.rep` para que se abra con `Crono Analysis`, por lo que es necesario  realizar la asociación manulmente. Una vez hecha esta asociación, ya se pueden abrir los informes directamente desde el explorador de archivos.

Recordar también que el ejecutable se encuentra en esta ubicación:

`C:\Users\_USUARIO_\AppData\Local\CronoAnalysis\CronoAnalysis.exe`
