### ISSUE TITLE
Crono web - no funciona l'ordenació per mesos

### ISSUE THREAD

**Issue by aseques** [bifacil/CronoSupport#45]
No es pot ordenar en el crono web per mesos.

![ksnip_tmp_HVowow](https://user-images.githubusercontent.com/555542/114053343-28f7b600-988f-11eb-9594-31b17a16dc36.png)

**Comment by bifacil** [comment]
La ordenació dels mesos es defineix en el catàleg.

Desde Crono Metadata has de definir el "camp d'ordenació".

![image](https://user-images.githubusercontent.com/4572969/114529956-c74a9980-9c4a-11eb-9111-8172a8e35dc4.png)

Aqui s'explica: https://businessintelligence.es/help/metadata/#ordenacion-de-los-meses
