### ISSUE TITLE
Crono web - caldria poder forçar una selecció única

### ISSUE THREAD

**Issue by aseques** [bifacil/CronoSupport#46]
Hi ha la opció de selecció obligatoria, aniria molt bé tenir la opció de selecció unica (tipus radio button), és una manera de reduir el numero de dades a carregar en catàlegs grans.
![ksnip_tmp_poaICT](https://user-images.githubusercontent.com/555542/114053671-72480580-988f-11eb-9b71-fee6ed780cc2.png)

**Comment by bifacil** [comment]
Hola, 

Em sembla una opción molt interessant. Efectivament, aquesta opció encara no existeix. Ho farem properament!

Gràcies per perguntar!

Suposo que ja ho saps, però hi ha una opció semblant en els filtres:

![image](https://user-images.githubusercontent.com/4572969/114529450-3ecbf900-9c4a-11eb-813c-5ae70acbc9fa.png)

Però ja entenc que no és això el que demanes...

**Comment by bifacil** [comment]
Añadiremos una nueva opción avanzada (y reordenaremos las existentes)

![image](https://user-images.githubusercontent.com/4572969/115913737-4624ab00-a471-11eb-9923-eca2707e0422.png)

**Comment by bifacil** [comment]
Esta opción ya está implementada en la versión 21.17. Ahora es posible seleccionar la entre "Selección múltiple" o "Selección simple". La nueva opción está en "Propiedades de panel":

![image](https://user-images.githubusercontent.com/4572969/116429787-8061c400-a846-11eb-863c-f0067d5a6cfb.png)


Por defecto, los nuevos paneles permiten la selección múltiple.

**Comment by bifacil** [comment]
Tanco!
