### ISSUE TITLE
Problema al duplicar consulta

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#5]
D. detactado un problema al duplicar paneles.

Tras duplicar un panel, si se añade una columna nueva, no se muestran sus valores. El siguiente vídeo muestra el problema utilizando el catálogo de La biblio:

https://www.screencast.com/t/s6n4IqQpDce

El problema es que no se actualiza porque no se ha ejecutado la consultat automáticamente al añadir la columna.

**Comment by sergiodebst** [comment]
Esto queda solucionado a partir de la versión 20.29

**Comment by bifacil** [comment]
OK. La versión ya está publicada y funciona desde hace unas semanas. Cierro.
