### ISSUE TITLE
La búsqueda en el catálogo ha dejado de funcionar

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#56]
Nos comunican que la búsqueda en el catálogo no funciona.

Tras eliminar la búsqueda, las carpeta quedan vacías.

El problema es  fácilmente reproducible.

![busqueda](https://user-images.githubusercontent.com/4572969/125050513-4dd41300-e0a2-11eb-95c8-46f496559d5a.gif)

**Comment by sergiodebst** [comment]
Este bug queda resuelto a partir de la versión 21.29

**Comment by bifacil** [comment]
La actualización ya está publicada con esta corrección incluída.
