### ISSUE TITLE
No se respeta la configuración regional del equipo (separador decimal)

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#6]
En Español de Honduras el separador decimal es el punto y el separador de miles es la coma.

Así está definido en la configuración regional del equipo.

Sin embargo, Crono muestra la configuración regional de España.

![image](https://user-images.githubusercontent.com/4572969/90455965-ca12e000-e0f7-11ea-8dc9-8262ba223c11.png)

Este no es el comportamiento esperado. Crono Analysis debe mostrar fechas y números según la configuración regional del equipo.

**Comment by bifacil** [comment]
La aplicación de configuración regional la tienen en cuenta otras aplicaciones:

![image](https://user-images.githubusercontent.com/4572969/91034203-e8e80980-e604-11ea-9da6-56a826acaa01.png)

**Comment by sergiodebst** [comment]
Este problema quedará resuelto a partir de la versión 20.35

**Comment by bifacil** [comment]
Aún no aparece correctamente, creo.

![image](https://user-images.githubusercontent.com/4572969/91112317-15426b00-e683-11ea-8941-f2ffed0e286e.png)

**Comment by sergiodebst** [comment]
Si funciona.
![imagen](https://user-images.githubusercontent.com/5172886/91150656-f6f96100-e6bc-11ea-8f9c-810ca091ca2a.png)

Modificar esa configuración regional en windows requiere reiniciar la aplicación.
Además en la configuración de idioma en la aplicación también debe estar seleccionado idioma del sistema, ya que seleccionar otro idioma aquí sobrescribiria esta configuración (y este cambio en este caso también requeriría reiniciar la aplicación)...
![imagen](https://user-images.githubusercontent.com/5172886/91150950-548dad80-e6bd-11ea-8309-8db768dd0713.png)

**Comment by bifacil** [comment]
Ok. De todos modos, creo que este no es el comportamiento esperado. El "idioma de la interfaz" de "opciones generales" no debe afectar al formato de los números.

![image](https://user-images.githubusercontent.com/4572969/91284231-e95edc80-e78b-11ea-8673-48e94225db17.png)

La configuración regional (formato de fechas, suparador de miles, separador decimal, ...) lo determina única y exclusivamente la configuración de Windows del equipo:

![image](https://user-images.githubusercontent.com/4572969/91284375-1b703e80-e78c-11ea-8c09-5ffe0e74b76a.png)

La única excelción es el símbolo de la moneda, que se puede configurar (y se recomienda hacerlo) en el catálogo o en el informe.


![image](https://user-images.githubusercontent.com/4572969/91284567-596d6280-e78c-11ea-87c2-2eb2831cb106.png)

**Comment by sergiodebst** [comment]
A partir de la versión 20.35.2000 la configuración de idioma de la aplicación ya no afectará al formato de los datos que por defecto se mostrarán usando la configuración regional de Windows.

**Comment by bifacil** [comment]
Ya está solucionado.

![image](https://user-images.githubusercontent.com/4572969/91362030-d4b92d80-e7f9-11ea-9f72-7dd703ac5adf.png)


Cierro.
