### ISSUE TITLE
Error al Intentar agregar columna calculada CRONO Analysis 22.5

### ISSUE THREAD

**Issue by jaguilarIMHN** [bifacil/CronoSupport#68]
Actualmente al tratar de agregar una columna calculada muestra un error y no se agrega la columna.

![image](https://user-images.githubusercontent.com/71401091/154289523-3898d50a-b210-4bf8-adb8-d94c545d27eb.png)

![image](https://user-images.githubusercontent.com/71401091/154289802-84c7a9e1-020d-427d-8615-e920854fff4c.png)

**Comment by bifacil** [comment]
Hola, 

El problema ocurría únicamente con la fórmula "Porcentaje del total"

![image](https://user-images.githubusercontent.com/4572969/154314538-d535284d-db48-4304-9525-d10e4a1299bf.png)

Está resuelto en la versión a partir de la versión `22.7.1000` de Crono Analysis.

El otro problema que me has comentado, referente a la impersonlaización en Crono Server (a partir `22.3`) no tiene nada que ver. Lo seguimos investigando.

**Comment by bifacil** [comment]
Hemos verificado que todos los caasos están solucionados en la última actualización. Cerramos.

**Comment by jaguilarIMHN** [comment]
He problema fue resuelto, muchas gracias !
