### ISSUE TITLE
Error al utilizar filtro con lista mas de 50 registros

### ISSUE THREAD

**Issue by jaguilarIMHN** [bifacil/CronoSupport#69]
Estoy reportando un error que ocurre al intentar trabajar con filtro de 50 registros 

El error mostrado es el siguiente:

![image](https://user-images.githubusercontent.com/71401091/154698278-309d11af-9694-4e03-9a6d-4c8fa13a1871.png)

**Comment by bifacil** [comment]
No creo que el problema sea el número de registros seleccionados.

Haznos llegar la query que genera y el mensaje exacto del servidor.

![image](https://user-images.githubusercontent.com/4572969/154970263-6b356e29-5f3e-412d-a599-6c2c2b1c4b89.png)

**Comment by bifacil** [comment]
El problema es que la query generada, una vez "comprimida", es demasiado larga para formar parte de una URL. La limitación es de 2048 caracteres.

Es una configuración predeterminada del IIS:

![image](https://user-images.githubusercontent.com/4572969/154984060-25389ec6-a27f-4280-8fbb-3e400ba3b87a.png)


Una posible solución es aumentar ese parámetro del IIS.

De todos modos, estudiaremos alguna solución alternativa para que esta limitación no afecta  a las comunicaciones entre en servidor de Crono y el cliente. Tal vez en lugar de peticiones 'GET' debería hacer peticiones 'POST'....

**Comment by bifacil** [comment]
Otro cliente se ha encontrado con la misma incidencia:

![image](https://user-images.githubusercontent.com/4572969/204031547-1adac546-00aa-40fe-9a4c-a42ddbea9725.png)

**Comment by bifacil** [comment]
Hemos solucionado esta problemática y publicaremos la actualización esta misma semana.

A partir de ahora las peticiones al servidor se hacen mediante POST (en en lugar de GET). No es un cambio importante pero requiere actualizar todos los servidores a la versión 22.11 o superior. 

![image](https://user-images.githubusercontent.com/4572969/226425235-bd8c7663-e6ea-45b8-acdb-1f62961838a4.png)

Actualizar es rápido y sin problemas o migraciones asociadas. Sencillamente, hay que abrir Crono Administrador y seleccionar la última versión.

Si no se actualiza Crono Analysis dejará de funcionar tras la próxima actualización.

**Comment by bifacil** [comment]
Este tema ya está solucionado tras la última actualización.
