### ISSUE TITLE
Error apertura Reportes en CRONO Server 22.7

### ISSUE THREAD

**Issue by jaguilarIMHN** [bifacil/CronoSupport#70]
Buen día,

Los usuarios me están reportando inconveniente al momento abrir un reporte se muestra mala definición en el catalogo.

la version actual es 22.7.0
He tenido que instalar la version 22.51.0

**Comment by bifacil** [comment]
Necesitamos el mensaje exacto que les aparece para identificar el problema.

**Comment by bifacil** [comment]
Hemos podido aislar reproducir el problema.

![image](https://user-images.githubusercontent.com/4572969/154984728-299a98a2-3778-4964-a682-d289707d66da.png)

Crono Server sirve correctamente los catálogos, pero en algunos casos no puede servir los informes.

En este caso, así está configurado el catálogo en el informe:

![image](https://user-images.githubusercontent.com/4572969/154985568-8a9eea71-fca9-46b8-a6dd-557ef8c43dec.png)

**Comment by bifacil** [comment]
El problema está resuelto en la versión `22.8.1000`
