### ISSUE TITLE
No se actualiza automáticamente

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#73]
Algunos usuarios nos están reportando este problema:

![image](https://user-images.githubusercontent.com/4572969/165961509-69c3423d-fc13-4948-97a5-0cc93229aafd.png)

**Comment by bifacil** [comment]
El problema es que todo y existir una actualización la aplicación hace tiempo que no se actualiza y requiere actualizarse.

El caso es extraño pues solo ocurre en unos pocos usuarios, mientras otros se actualizaron correctamente a su debido tiempo.

La manera más sencilla de resolver el problema es actualizarse manualmente a la última versión de Crono Analysys desde la página de descargas:

https://businessintelligence.es/downloads/

**Comment by teresaalvarezymas** [comment]
Partiendo del enlace enviado por email (https://s3.eu-west-1.amazonaws.com/downloads.crono.net/updates/CronoAnalysis/SetupCronoAnalysis-22.13.0.exe) se genera el siguiente e error:
![image](https://user-images.githubusercontent.com/84377053/166412596-4218dea9-5a52-4493-a2ee-da5910654555.png)

![image](https://user-images.githubusercontent.com/84377053/166413050-750d17cc-ad3a-4aff-8d91-91da3689ab60.png)

**Comment by bifacil** [comment]
No hemos podido reproducir correctamente el problema. De hecho, al intentar instalar de nuevo Crono Analysis se ha instalado correctamente.

Si volviera a ocurrir una solución sería eliminar completamente la carpeta `[AppData]/Local/CronoAnalysis`
