### ISSUE TITLE
Problema al exportar a Excel

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#74]
Un usuario nos informa que aparece este mensaje de error al intentar exportar a Excel:

![image](https://user-images.githubusercontent.com/4572969/165963581-2bc35259-5c0a-4c42-91e4-af038db140be.png)

Hemos solicitado más información para poder reproducirlo y corregirlo.

**Comment by teresaalvarezymas** [comment]
En un informe con varios paneles, al tratar de exportar a Excel el primero de ellos aparece el mensaje que genera la incidencia.
Hago captura de pantalla completa para que se puedan apreciar los nombres de la hoja y de cada uno de los paneles.

![image](https://user-images.githubusercontent.com/84377053/166412157-4ee4aeed-5952-46a3-9214-c610665e81c7.png)

Tanto el nombre de la hoja como el del panel activo ("Clasificación de artículos") tienen una longitud de 26 caracteres.

**Comment by bifacil** [comment]
Hola, 

El problema era el panel "INFORMACION POR CENTRO LOGISTICO". Ese literal tiene más 32 caracteres y el nombre de una hoja de Excel no puede ser tan largo.

El nombre "COMPRAS/VENTAS" tampoco es válido, pues la barra no puede emplearse en el nombre de una hoja.

Al exportar una hoja de Crono lo que hace Crono es exportar cada uno de sus paneles en una hoja de Excel distinta y utiliza el nombre del panel como nombre de la hoja.

Para solucionarlo, tandrás que cambiar el nombre de esos dos paneles conflictivos...
